version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8023:8023"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_LOGIN: ${SMTP_LOGIN}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SECRET: ${SECRET}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
